import feladatok
#feladatok.fel1()
#feladatok.fel2(1234)
#feladatok.fel3()
#feladatok.fel4()
#feladatok.fel5()
#feladatok.fel6()
#feladatok.fel7()
#feladatok.kiallitasfel()
#feladatok.fel8()
#feladatok.fel9()
#feladatok.fel10(nem sikerült)
#feladatok.fel11()
#feladatok.fel12(nincs kész)
#feladatok.fel13(nincs kész)
