import feladatok
import gyakorlas
#gyakorlas.veletlen()
gyakorlas.fel1()
gyakorlas.fel2()
gyakorlas.fel3()
gyakorlas.fel4()
gyakorlas.fel5("ládiá")
#feladatok.fel1()
#feladatok.fel2(12341)
#feladatok.fel3()
#feladatok.fel4()
#feladatok.fel5()
#feladatok.fel6()
#feladatok.fel7()
#feladatok.kiallitasfel()
#feladatok.fel8()
#feladatok.fel9()
#feladatok.fel10()
#feladatok.fel11()
#feladatok.fel12(nincs kész)
#feladatok.fel13(nincs kész)
